spring:
  application:
    name: peminjaman

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 1
        max-concurrency: 5

  # Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: thefruss032@gmail.com      # ganti dengan email kamu
    password: dixvfwdefnujufmy          # ganti dengan app password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


# Logging (opsional)
logging:
  level:
    org.springframework: INFO
