pipeline {
    agent any
    tools { maven 'Maven3'; jdk 'JDK22' }
    environment {
        DOCKER_HUB_USER = "thefruss032"
        IMAGE_NAME = "api-gateway"
        REGISTRY_CREDS = "docker-hub-creds"
    }
    stages {
        stage('Build JAR') { steps { bat 'mvn clean package -DskipTests' } }
        stage('Docker Build') { steps { bat "docker build -t ${DOCKER_HUB_USER}/${IMAGE_NAME}:${env.BUILD_NUMBER} ." } }
        stage('Push to Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: REGISTRY_CREDS, passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                        bat "docker login -u %USER% -p %PASS%"
                        bat "docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}:${env.BUILD_NUMBER}"
                    }
                }
            }
        }
        stage('Deploy to K8s') {
            steps {
                // Sesuai dengan 04-gateway.yaml (deployment name: gateway-app, container name: gateway)
                bat "kubectl set image deployment/gateway-app gateway=${DOCKER_HUB_USER}/${IMAGE_NAME}:${env.BUILD_NUMBER} -n perpustakaan-ns"
                bat "kubectl rollout status deployment/gateway-app -n perpustakaan-ns"
            }
        }
    }
}