spring:
  application:
    name: rabbitmq
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    template:
      exchange: order.exchange
    listener:
      simple:
        default-requeue-rejected: false
  mail:   # ← pindahkan ke dalam spring, bukan di bawah app
    host: smtp.gmail.com
    port: 587
    username: thefruss032@gmail.com   # ganti dengan email Gmail kamu
    password: dixvfwdefnujufmy       # tanpa spasi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  rabbitmq:
    queue: order_queue
    exchange: order_exchange
    routing-key: order_routingKey

logging:
  level:
    com.dika.rabbitmq: DEBUG
